# -*- coding: utf-8 -*-
"""notebook_2_Jaswanthi_Murugudu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zdZ4fp5TiUSQs8DwSsqJh4c3-ZzsEyL4
"""

# Import Libraries
import os
import requests
import smtplib
import ssl
from email.mime.text import MIMEText

#  Define Constants
WEATHER_API_KEY = "5a7324e7d0c8a05288f855abdc75d75f"
CITY = "Bangalore"
SENDER_EMAIL = "murugudujaswanthi@gmail.com"
APP_PASSWORD = "rfym irsg nyoj ysic" #app password

#  Function: Fetch Weather Data
def fetch_weather(city, api_key):
    url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}&units=metric"
    response = requests.get(url)

    if response.status_code == 200:
        return response.json()
    else:
        print("❌ Error fetching weather data!")
        print("Response Code:", response.status_code)
        print("Error Message:", response.json())  # Show full error details
        return None

# Function: Send Email
def send_email(recipient_email, subject, message):
    msg = MIMEText(message)
    msg["From"] = SENDER_EMAIL
    msg["To"] = recipient_email
    msg["Subject"] = subject

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            #server.start()  # Upgrade the connection to secure
            server.login(SENDER_EMAIL, APP_PASSWORD)
            server.sendmail(SENDER_EMAIL, recipient_email, msg.as_string())
        print("✅ Email sent successfully!")
    except Exception as error:
        print(f"❌ Error sending email: {error}")

# Run the Process
if __name__ == "__main__":
    weather_data = fetch_weather(CITY, WEATHER_API_KEY)

    if weather_data:
        temp = weather_data["main"]["temp"]
        description = weather_data["weather"][0]["description"]
        message = f"🌤 Weather Update for {CITY}\nTemperature: {temp}°C\nCondition: {description}"

        RECIPIENT_EMAIL = "jaswanthi.murugudu04@gmail.com"  # recipient email
        SUBJECT = f"Weather Report for {CITY}"

        send_email(RECIPIENT_EMAIL, SUBJECT, message)