# -*- coding: utf-8 -*-
"""notebook_3_Jaswanthi_Murugudu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143OfHswfS8ibPYk-5pRwg3uooIFIslW6
"""

# Import Required Libraries
import requests
import smtplib
import ssl
from email.mime.text import MIMEText

# Define Constants
WEATHER_API_KEY = "5a7324e7d0c8a05288f855abdc75d75f"
SENDER_EMAIL = "murugudujaswanthi@gmail.com"
APP_PASSWORD = "rfym irsg nyoj ysic"  #  App Password

# Take Inputs from User
latitude = input("Enter Latitude: ")
longitude = input("Enter Longitude: ")
recipient_email = input("Enter Recipient Email: ")

# Function: Fetch Weather Data using Latitude & Longitude
def fetch_weather(lat, lon, api_key):
    url = f"http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}&units=metric"
    response = requests.get(url)

    if response.status_code == 200:
        return response.json()
    else:
        print("❌ Error fetching weather data!")
        print("Response Code:", response.status_code)
        print("Error Message:", response.json())  # full error details
        return None

# Function: Send Email
def send_email(recipient_email, subject, message):
    msg = MIMEText(message)
    msg["From"] = SENDER_EMAIL
    msg["To"] = recipient_email
    msg["Subject"] = subject

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(SENDER_EMAIL, APP_PASSWORD)
            server.sendmail(SENDER_EMAIL, recipient_email, msg.as_string())
        print("✅ Email sent successfully!")
    except Exception as error:
        print(f"❌ Error sending email: {error}")

# Run the Process
weather_data = fetch_weather(latitude, longitude, WEATHER_API_KEY)

if weather_data:
    city_name = weather_data["name"]
    temp = weather_data["main"]["temp"]
    description = weather_data["weather"][0]["description"]

    message = f"🌤 Weather Update for {city_name} \nLatitude: {latitude}, Longitude: {longitude}\nTemperature: {temp}°C\nCondition: {description}"
    subject = f"Weather Report for {city_name}"

    send_email(recipient_email, subject, message)